### ISSUE TITLE
[BUG] Module starts an encounter when the gamemaster logs in

### ISSUE THREAD

**Issue by Lethay** [arcanistzed/scs#13]
**Describe the bug**
Module forces combat to start on login

**To Reproduce**
Activate module and open Foundry. A new encounter is created. This is especially obvious if "hide if no combat" is enabled and "hide tracker" is disabled.
This occurs even if scs is the only active module.

**Details**
Foundry VTT version: v9, build 238
Module version: 2.12.0

**Comment by arcanistzed** [comment]
This is not a bug. It's a feature 😅

Is this not something you want to use?

It was added because SCS doesn't work with no combat enabled and it's not easy to start one with the Combat Tracker hidden.

**Comment by arcanistzed** [comment]
I could perhaps add an option to disable it or maybe tie that to the option for hiding the combat tracker (i.e. only enable it when the tracker is hidden).
Let me know your thoughts

**Comment by Lethay** [comment]
Ah, my apologies - of course it's a feature, as you obviously cannot start combat with no combat tracker!
I agree, it makes most sense to have that option tied to whether the combat tracker is hidden or not. If the user has un-hidden that, it implies they want to control the combat state themselves.

**Comment by Lethay** [comment]
I realised an additional problem that relates to this. The module does not check if the current user has permission to start an encounter before it tries to do it. My players all login after I have ended the encounter that SCS started, and they tell me that they're getting an error message that they don't have permission to begin an encounter.

**Comment by EsotericOdyssey** [comment]
> I could perhaps add an option to disable it or maybe tie that to the option for hiding the combat tracker (i.e. only enable it when the tracker is hidden). Let me know your thoughts

I would prefer there be an option to toggle for this, or to even just have it only do this behavior if the Combat Tracker is hidden since that's what it's meant for anyway, rather than it being hard-coded. The more configuration and control I can have over individual modules, the better IMO. This is currently interacting with a bug in another module I want to use for initiative/combat tracking, Lancer Initiative, where whenever a combat encounter is created, it starts with a hidden combatant named "Unknown Combatant" not linked to any actor or token (or, I assume it's not linked to anything, because it does this even if there are no actors or tokens or scenes in the world at all). It's nothing catastrophic but it's annoying to have that Unknown Combatant pop up every single time I log in or even just refresh the page.

**Comment by arcanistzed** [comment]
I plan to fix this by adding a new setting to enable automatically starting a Combat.
If you enable hiding the Combat Tracker, it will also enable this new setting unless you could force it to be disabled by disabling it again.

**Comment by Lethay** [comment]
#15 is a potential fix, which depends on the Hide Combat Tracker option. I had forgotten that, as you said in your last comment, you wished to make a new setting for this.
