### ISSUE TITLE
[FEAT] Separate movement/action locking

### ISSUE THREAD

**Issue by dirkson** [arcanistzed/scs#7]
The current implementation of action locking leaves a lot of spells/features undefined, with no combat phase that they can actually be used in. As a result we've had to disable action locking for the time being.

While, long term, fixing each one is clearly the right solution, in the short term it might be better to separate action locking from movement locking, as movement locking already works perfectly.

**Comment by arcanistzed** [comment]
Which ones are undefined? What do you have that can't be used in any phase?

If you want to disable Action Locking for a phase you can just change it's name slightly and the module will no longer recognize it (although changing the name of the Attacks phase will affect the HUD feature).

I'm not sure if I'm interested in allowing parts of Action Locking not to be used, since changing the phase names is a more efficient solution.

**Comment by dirkson** [comment]
Hmm. I like that. I can just set the magic phase to be a magic/misc phase, then, and keep movement/attacking phases distinct.

We had enough things (4-5?) that seemed to fall outside existing phases that it didn't occur to me to take notes. I'll keep an eye out for them in the future and do an update when I run across them.

Sorry for the long delay, I only jump back to D&D stuff every few days.
